changelog:
  exclude:
    authors: [dependabot, github-actions, pre-commit-ci]
  categories:
    - title: 🎉 New Features
      labels: [feature]
    - title: 🐛 Bug Fixes
      labels: [fix]
    - title: 🛠 Enhancements
      labels: [enhancement, DX, UX]
    - title: 📖 Documentation
      labels: [docs]
    - title: 🧹 House-Keeping
      labels: [housekeeping]
    - title: 🚀 Performance
      labels: [performance]
    - title: 💡 Refactoring
      labels: [refactor]
    - title: 🧪 Tests
      labels: [tests]
    - title: 💥 Breaking Changes
      labels: [breaking]
    - title: 🔒 Security Fixes
      labels: [security]
    - title: 🏥 Package Health
      labels: [pkg]
    - title: 🤷‍♂️ Other Changes
      labels: ["*"]
