#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

#running nose-tests
echo "Running nose tests. Please wait..."
nose_output=`nosetests --with-doctest 2>&1`
error=`echo "$nose_output" | grep Error`
if [ "$error" != "" ]; then
        echo "pymatgen nosetest has errors.  Error log: $nose_output" 
        exit 1
fi 
echo "pymatgen nosetest passed. Log: $nose_output" 
