# coding: utf-8
# Copyright (c) Pymatgen Development Team.
# Distributed under the terms of the MIT License.

from __future__ import division, print_function, unicode_literals, \
    absolute_import

import unittest
import os
import random
import json

import numpy as np
import pandas as pd
from ruamel.yaml import YAML
from pymatgen import Molecule, Element

from pymatgen.io.lammps.data import LammpsData, Topology, ForceField


test_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..",
                        "test_files", "lammps")


class LammpsDataTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.peptide = LammpsData.\
            from_file(filename=os.path.join(test_dir, "data.peptide"))
        cls.ethane = LammpsData.\
            from_file(filename=os.path.join(test_dir, "ethane.data"))
        cls.quartz = LammpsData.\
            from_file(filename=os.path.join(test_dir, "data.quartz"),
                      atom_style="atomic")
        cls.virus = LammpsData.\
            from_file(filename=os.path.join(test_dir, "virus.data"),
                      atom_style="angle")

    def test_get_string(self):
        pep = self.peptide.get_string(distance=7, velocity=5, charge=4)
        pep_lines = pep.split("\n")
        pep_kws = ["Masses", "Pair Coeffs", "Bond Coeffs", "Angle Coeffs",
                   "Dihedral Coeffs", "Improper Coeffs", "Atoms",
                   "Velocities", "Bonds", "Angles", "Dihedrals", "Impropers"]
        kw_inds = {l: i for i, l in enumerate(pep_lines) if l in pep_kws}
        # section sequence
        self.assertListEqual([k for k in sorted(kw_inds, key=kw_inds.get)],
                             pep_kws)
        # header
        pep_header = "\n".join(pep_lines[:kw_inds["Masses"]])
        pep_header_7 = """Generated by pymatgen.io.lammps.data.LammpsData

2004  atoms
1365  bonds
 786  angles
 207  dihedrals
  12  impropers

  14  atom types
  18  bond types
  31  angle types
  21  dihedral types
   2  improper types

36.8401940 64.2115600  xlo xhi
41.0136910 68.3850580  ylo yhi
29.7680950 57.1394620  zlo zhi
"""
        self.assertEqual(pep_header, pep_header_7)
        # int vs float for coeffs
        pep_dihedral_coeff = pep_lines[kw_inds["Dihedral Coeffs"] + 2]
        self.assertEqual(pep_dihedral_coeff, "1   0.200  1  180  1.0")
        # distance and charge
        pep_atom = pep_lines[kw_inds["Atoms"] + 2]
        self.assertEqual(pep_atom, "1       1   1  0.5100 43.9999300 "
                                   "58.5267800 36.7855000  0  0  0")
        # velocity
        pep_velo = pep_lines[kw_inds["Velocities"] + 2]
        self.assertEqual(pep_velo, "1    -0.00067 -0.00282  0.00383")
        # no floats in topology sections
        pep_topos = "\n".join(pep_lines[kw_inds["Bonds"]:])
        self.assertNotIn(".", pep_topos)

        c2h6 = self.ethane.get_string(distance=5, charge=3)
        c2h6_lines = c2h6.split("\n")
        c2h6_kws = ["Masses", "Pair Coeffs", "Bond Coeffs", "Angle Coeffs",
                    "Dihedral Coeffs", "Improper Coeffs", "BondBond Coeffs",
                    "BondAngle Coeffs", "MiddleBondTorsion Coeffs",
                    "EndBondTorsion Coeffs", "AngleTorsion Coeffs",
                    "AngleAngleTorsion Coeffs", "BondBond13 Coeffs",
                    "AngleAngle Coeffs", "Atoms", "Bonds", "Angles",
                    "Dihedrals", "Impropers"]
        kw_inds = {l: i for i, l in enumerate(c2h6_lines) if l in c2h6_kws}
        # section sequence
        self.assertListEqual([k for k in sorted(kw_inds, key=kw_inds.get)],
                             c2h6_kws)
        # header
        c2h6_header = "\n".join(c2h6_lines[:kw_inds["Masses"]])
        c2h6_header_5 = """Generated by pymatgen.io.lammps.data.LammpsData

 8  atoms
 7  bonds
12  angles
 9  dihedrals
 8  impropers

 2  atom types
 2  bond types
 2  angle types
 1  dihedral types
 2  improper types

0.21455 10.21454  xlo xhi
0.11418 10.11418  ylo yhi
-10.00014 -0.00015  zlo zhi
"""
        self.assertEqual(c2h6_header, c2h6_header_5)
        # distance and charge
        c2h6_atom = c2h6_lines[kw_inds["Atoms"] + 2]
        self.assertEqual(c2h6_atom, "1  1  1 -0.080 4.46291 5.14833 -5.00041"
                                    "  0  0  0")
        # no floats in topology sections
        c2h6_topos = "\n".join(c2h6_lines[kw_inds["Bonds"]:])
        self.assertNotIn(".", c2h6_topos)

        quartz = self.quartz.get_string(distance=4)
        quartz_lines = quartz.split("\n")
        quartz_kws = ["Masses", "Atoms"]
        kw_inds = {l: i for i, l in enumerate(quartz_lines) if l in quartz_kws}
        # header
        quartz_header = "\n".join(quartz_lines[:kw_inds["Masses"]])
        quartz_header_4 = """Generated by pymatgen.io.lammps.data.LammpsData

9  atoms

2  atom types

0.0000 4.9134  xlo xhi
0.0000 4.2551  ylo yhi
0.0000 5.4052  zlo zhi
-2.4567 0.0000 0.0000  xy xz yz
"""
        self.assertEqual(quartz_header, quartz_header_4)
        # distance
        quartz_atom = quartz_lines[kw_inds["Atoms"] + 2]
        self.assertEqual(quartz_atom, "1  1  2.3088  0.0000  3.6035")

        virus = self.virus.get_string()
        virus_lines = virus.split("\n")
        pairij_coeff = virus_lines[virus_lines.index("PairIJ Coeffs") + 5]
        self.assertEqual(pairij_coeff, "1  4  1  1.000  1.12250")

    def test_write_file(self):
        filename1 = "test1.data"
        self.ethane.write_file(filename=filename1)
        c2h6 = LammpsData.from_file(filename1)
        pd.testing.assert_frame_equal(c2h6.masses, self.ethane.masses)
        pd.testing.assert_frame_equal(c2h6.atoms, self.ethane.atoms)
        ff_kw = random.sample(self.ethane.force_field.keys(), 1)[0]
        pd.testing.assert_frame_equal(c2h6.force_field[ff_kw],
                                      self.ethane.force_field[ff_kw], ff_kw)
        topo_kw = random.sample(self.ethane.topology.keys(), 1)[0]
        pd.testing.assert_frame_equal(c2h6.topology[topo_kw],
                                      self.ethane.topology[topo_kw], topo_kw)
        filename2 = "test2.data"
        self.virus.write_file(filename=filename2)
        v = LammpsData.from_file(filename2, atom_style="angle")
        pd.testing.assert_frame_equal(v.force_field["PairIJ Coeffs"],
                                      self.virus.force_field["PairIJ Coeffs"])

    def test_from_file(self):
        # general tests
        pep = self.peptide
        # header stats and Nos. of columns
        self.assertEqual(pep.masses.shape, (14, 1))
        self.assertEqual(pep.atoms.shape, (2004, 9))
        self.assertListEqual(list(pep.atoms.columns),
                             ["molecule-ID", "type", "q", "x", "y", "z",
                              "nx", "ny", "nz"])
        topo = pep.topology
        self.assertEqual(topo["Bonds"].shape, (1365, 3))
        self.assertEqual(topo["Angles"].shape, (786, 4))
        self.assertEqual(topo["Dihedrals"].shape, (207, 5))
        self.assertEqual(topo["Impropers"].shape, (12, 5))
        ff = pep.force_field
        self.assertEqual(ff["Pair Coeffs"].shape, (14, 4))
        self.assertEqual(ff["Bond Coeffs"].shape, (18, 2))
        self.assertEqual(ff["Angle Coeffs"].shape, (31, 4))
        self.assertEqual(ff["Dihedral Coeffs"].shape, (21, 4))
        self.assertEqual(ff["Improper Coeffs"].shape, (2, 2))
        # header box
        np.testing.assert_array_equal(pep.box_bounds,
                                      [[36.840194, 64.211560],
                                       [41.013691, 68.385058],
                                       [29.768095, 57.139462]])
        # body
        self.assertEqual(pep.masses.at[7, "mass"], 12.0110)
        self.assertEqual(ff["Pair Coeffs"].at[9, "coeff3"], 0.152100)
        self.assertEqual(ff["Bond Coeffs"].at[5, "coeff2"], 1.430000)
        self.assertEqual(ff["Angle Coeffs"].at[21, "coeff2"], 120.000000)
        self.assertEqual(ff["Dihedral Coeffs"].at[10, "coeff1"], 0.040000)
        self.assertEqual(ff["Improper Coeffs"].at[2, "coeff1"], 20.000000)
        self.assertEqual(pep.atoms.at[29, "molecule-ID"], 1)
        self.assertEqual(pep.atoms.at[29, "type"], 7)
        self.assertEqual(pep.atoms.at[29, "q"], -0.020)
        self.assertAlmostEqual(pep.atoms.at[29, "x"], 42.96709)
        self.assertEqual(pep.atoms.at[1808, "molecule-ID"], 576)
        self.assertEqual(pep.atoms.at[1808, "type"], 14)
        self.assertAlmostEqual(pep.atoms.at[1808, "y"], 58.64352)
        self.assertEqual(pep.atoms.at[1808, "nx"], -1)
        self.assertAlmostEqual(pep.velocities.at[527, "vz"], -0.010889)
        self.assertEqual(topo["Bonds"].at[47, "type"], 8)
        self.assertEqual(topo["Bonds"].at[47, "atom2"], 54)
        self.assertEqual(topo["Bonds"].at[953, "atom1"], 1384)
        self.assertEqual(topo["Angles"].at[105, "type"], 19)
        self.assertEqual(topo["Angles"].at[105, "atom3"], 51)
        self.assertEqual(topo["Angles"].at[376, "atom2"], 772)
        self.assertEqual(topo["Dihedrals"].at[151, "type"], 14)
        self.assertEqual(topo["Dihedrals"].at[151, "atom4"], 51)
        self.assertEqual(topo["Impropers"].at[4, "atom4"], 32)
        # class 2 and comments
        ethane = self.ethane
        self.assertEqual(ethane.masses.shape, (2, 1))
        self.assertEqual(ethane.atoms.shape, (8, 9))
        class2 = ethane.force_field
        self.assertEqual(class2["Pair Coeffs"].shape, (2, 2))
        self.assertEqual(class2["Bond Coeffs"].shape, (2, 4))
        self.assertEqual(class2["Angle Coeffs"].shape, (2, 4))
        self.assertEqual(class2["Dihedral Coeffs"].shape, (1, 6))
        self.assertEqual(class2["Improper Coeffs"].shape, (2, 2))
        self.assertEqual(class2["BondBond Coeffs"].at[2, "coeff3"], 1.1010)
        self.assertEqual(class2["BondAngle Coeffs"].at[2, "coeff4"], 1.1010)
        self.assertEqual(class2["AngleAngle Coeffs"].at[2, "coeff6"],
                         107.6600)
        self.assertEqual(class2["AngleAngle Coeffs"].at[2, "coeff6"],
                         107.6600)
        self.assertEqual(class2["AngleAngleTorsion Coeffs"].at[1, "coeff3"],
                         110.7700)
        self.assertEqual(class2["EndBondTorsion Coeffs"].at[1, "coeff8"],
                         1.1010)
        self.assertEqual(class2["MiddleBondTorsion Coeffs"].at[1, "coeff4"],
                         1.5300)
        self.assertEqual(class2["BondBond13 Coeffs"].at[1, "coeff3"], 1.1010)
        self.assertEqual(class2["AngleTorsion Coeffs"].at[1, "coeff8"],
                         110.7700)
        # box_tilt and another atom_style
        quartz = self.quartz
        np.testing.assert_array_equal(quartz.box_tilt, [-2.456700, 0.0, 0.0])
        self.assertListEqual(list(quartz.atoms.columns),
                             ["type", "x", "y", "z"])
        self.assertAlmostEqual(quartz.atoms.at[7, "x"], 0.299963)
        # PairIJ Coeffs section
        virus = self.virus
        pairij = virus.force_field["PairIJ Coeffs"]
        self.assertEqual(pairij.at[7, "id1"], 3)
        self.assertEqual(pairij.at[7, "id2"], 3)
        self.assertEqual(pairij.at[7, "coeff2"], 2.1)
        # sort_id
        nvt = LammpsData.from_file(filename=os.path.join(test_dir,
                                                         "nvt.data"),
                                   sort_id=True)
        atom_id = random.randint(1, 648)
        self.assertEqual(nvt.atoms.loc[atom_id].name, atom_id)

    def test_from_ff_and_topologies(self):
        ff = ForceField.from_file(os.path.join(test_dir, "ff_peptide.yaml"))
        with open(os.path.join(test_dir, "topologies_peptide.json")) as f:
            topo_dicts = json.load(f)
        topologies = [Topology.from_dict(d) for d in topo_dicts]
        peptide = LammpsData.\
            from_ff_and_topologies(ff=ff, topologies=topologies,
                                   box_bounds=[[-50, 150]] * 3)
        self.assertListEqual(peptide.masses, ff.masses)
        force_field = ff.get_pair_coeffs()
        for kw in ff.mol_coeffs.keys():
            sec, _ = ff.get_coeffs_and_mapper(kw)
            force_field.update(sec)
        self.assertDictEqual(peptide.force_field, force_field)
        back_atom_map = {v: k for k, v in ff.atom_map.items()}
        # test the 1st topology, the peptide
        pep = topologies[0]
        # atoms and velocities sections
        i = random.randint(0, len(pep.sites) - 1)
        site = pep.sites[i]
        in_atoms = peptide.atoms[i]
        self.assertEqual(in_atoms["molecule-ID"], 1)
        self.assertEqual(in_atoms["id"], i + 1)
        self.assertEqual(in_atoms["type"],
                         ff.atom_map[site.properties["ff_map"]])
        self.assertEqual(in_atoms["q"], pep.charges[i])
        self.assertEqual(in_atoms["x"], site.x)
        self.assertEqual(in_atoms["y"], site.y)
        self.assertEqual(in_atoms["z"], site.z)
        in_velos = peptide.velocities[i]
        self.assertEqual(in_velos["id"], i + 1)
        self.assertListEqual(in_velos["velocity"], pep.velocities[i])
        # topology sections
        for t in ["Bond", "Angle", "Dihedral", "Improper"]:
            topo_sec = "%ss" % t
            ff_sec = "%s Coeffs" % t
            kw = t.lower()
            i = random.randint(0, len(pep.topologies[topo_sec]) - 1)
            sample = pep.topologies[topo_sec][i]
            in_topos = peptide.topology[topo_sec][i]
            self.assertEqual(in_topos["id"], i + 1, "%s" % t)
            np.testing.assert_array_equal(in_topos[kw],
                                          np.array(sample) + 1, "%s" % t)
            topo_type_id = in_topos["type"]
            types = ff.mol_coeffs[ff_sec][topo_type_id - 1]["types"]
            sample_type = tuple([pep.sites[j].properties["ff_map"]
                                 for j in sample])
            self.assertIn(sample_type, types, "%s" % t)
        # test a random solvent (water) molecule
        i = random.randint(1, len(topologies) - 1)
        solv = topologies[i]
        stack = {"Atoms": 0, "Bonds": 0, "Angles": 0}
        for topo in topologies[:i]:
            stack["Atoms"] += len(topo.sites)
            stack["Bonds"] += len(topo.topologies["Bonds"])
            stack["Angles"] += len(topo.topologies["Angles"])
        # atoms and velocities sections
        in_atoms = [d for d in peptide.atoms if d["molecule-ID"] == i + 1]
        self.assertEqual(len(in_atoms), len(solv.sites))
        aids, types, charges, coords = [], [], [], []
        for d in in_atoms:
            aids.append(d["id"])
            types.append(d["type"])
            charges.append(d["q"])
            coords.append([d["x"], d["y"], d["z"]])
        np.testing.assert_array_equal(aids, np.arange(len(solv.sites))
                                      + stack["Atoms"] + 1)
        self.assertListEqual(types, [ff.atom_map[t] for t in solv.types])
        self.assertListEqual(charges, solv.charges)
        np.testing.assert_array_equal(coords, solv.sites.cart_coords)
        in_velos = peptide.velocities[stack["Atoms"]: stack["Atoms"]
                                                      + len(in_atoms)]
        vids, velocities = [], []
        for d in in_velos:
            vids.append(d["id"])
            velocities.append(d["velocity"])
        self.assertListEqual(vids, aids)
        np.testing.assert_array_equal(velocities, solv.velocities)
        # topology sections
        for t in ["Bond", "Angle"]:
            topo_sec = "%ss" % t
            ff_sec = "%s Coeffs" % t
            kw = t.lower()
            sample = solv.topologies[topo_sec][0]
            i = stack[topo_sec]
            in_topos = peptide.topology[topo_sec][i]
            self.assertEqual(in_topos["id"], i + 1, "%s" % t)
            np.testing.assert_array_equal(in_topos[kw], np.array(sample)
                                          + stack["Atoms"] + 1, "%s" % t)
            topo_type_id = in_topos["type"]
            types = ff.mol_coeffs[ff_sec][topo_type_id - 1]["types"]
            sample_type = tuple([solv.sites[j].properties["ff_map"]
                                 for j in sample])
            self.assertIn(sample_type, types, "%s" % t)

    def test_json_dict(self):
        encoded = json.dumps(self.ethane.as_dict())
        decoded = json.loads(encoded)
        c2h6 = LammpsData.from_dict(decoded)
        pd.testing.assert_frame_equal(c2h6.masses, self.ethane.masses)
        pd.testing.assert_frame_equal(c2h6.atoms, self.ethane.atoms)
        ff = self.ethane.force_field
        key, target_df = random.sample(ff.items(), 1)[0]
        self.assertIsNone(
            pd.testing.assert_frame_equal(c2h6.force_field[key], target_df,
                                          check_dtype=False),
            key
        )
        topo = self.ethane.topology
        key, target_df = random.sample(topo.items(), 1)[0]
        self.assertIsNone(
            pd.testing.assert_frame_equal(c2h6.topology[key], target_df),
            key
        )

    @classmethod
    def tearDownClass(cls):
        tmpfiles = ["test1.data", "test2.data"]
        for t in tmpfiles:
            if os.path.exists(t):
                os.remove(t)


class TopologyTest(unittest.TestCase):

    def test_init(self):
        inner_charge = np.random.rand(10) - 0.5
        outer_charge = np.random.rand(10) - 0.5
        inner_velo = np.random.rand(10, 3) - 0.5
        outer_velo = np.random.rand(10, 3) - 0.5
        m = Molecule(["H"] * 10, np.random.rand(10, 3) * 100,
                     site_properties={"ff_map": ["D"] * 10,
                                      "charge": inner_charge,
                                      "velocities": inner_velo})
        # q and v from site properties, while type from species_string
        topo = Topology(sites=m)
        self.assertListEqual(topo.types, ["H"] * 10)
        np.testing.assert_array_equal(topo.charges, inner_charge)
        np.testing.assert_array_equal(topo.velocities, inner_velo)
        # q and v from overriding, while type from site property
        topo_override = Topology(sites=m, atom_type="ff_map",
                                 charges=outer_charge,
                                 velocities=outer_velo)
        self.assertListEqual(topo_override.types, ["D"] * 10)
        np.testing.assert_array_equal(topo_override.charges, outer_charge)
        np.testing.assert_array_equal(topo_override.velocities, outer_velo)
        # test using a list of sites instead of SiteCollection
        topo_from_list = Topology(sites=m.sites)
        self.assertListEqual(topo_from_list.types, topo.types)
        np.testing.assert_array_equal(topo_from_list.charges, topo.charges)
        np.testing.assert_array_equal(topo_from_list.velocities,
                                      topo.velocities)

    def test_from_bonding(self):
        # He: no bonding topologies
        helium = Molecule(["He"], [[0, 0, 0]])
        topo_he = Topology.from_bonding(molecule=helium)
        self.assertIsNone(topo_he.topologies)
        # H2: 1 bond only
        hydrogen = Molecule(["H"] * 2, [[0, 0, 0], [0, 0, 0.7414]])
        topo_h = Topology.from_bonding(molecule=hydrogen)
        tp_h = topo_h.topologies
        self.assertListEqual(tp_h["Bonds"], [[0, 1]])
        self.assertNotIn("Angles", tp_h)
        self.assertNotIn("Dihedrals", tp_h)
        # water: 2 bonds and 1 angle only
        water = Molecule(["O", "H", "H"], [[0.0000, 0.0000, 0.1173],
                                           [0.0000, 0.7572, -0.4692],
                                           [0.0000, -0.7572, -0.4692]])
        topo_water = Topology.from_bonding(molecule=water)
        tp_water = topo_water.topologies
        self.assertListEqual(tp_water["Bonds"], [[0, 1], [0, 2]])
        self.assertListEqual(tp_water["Angles"], [[1, 0, 2]])
        self.assertNotIn("Dihedrals", tp_water)
        # EtOH
        etoh = Molecule(["C", "C", "O", "H", "H", "H", "H", "H", "H"],
                        [[1.1879, -0.3829, 0.0000],
                         [0.0000, 0.5526, 0.0000],
                         [-1.1867, -0.2472, 0.0000],
                         [-1.9237, 0.3850, 0.0000],
                         [2.0985, 0.2306, 0.0000],
                         [1.1184, -1.0093, 0.8869],
                         [1.1184, -1.0093, -0.8869],
                         [-0.0227, 1.1812, 0.8852],
                         [-0.0227, 1.1812, -0.8852]])
        topo_etoh = Topology.from_bonding(molecule=etoh)
        tp_etoh = topo_etoh.topologies
        self.assertEqual(len(tp_etoh["Bonds"]), 8)
        etoh_bonds = [[0, 1], [0, 4], [0, 5], [0, 6],
                      [1, 2], [1, 7], [1, 8], [2, 3]]
        np.testing.assert_array_equal(tp_etoh["Bonds"], etoh_bonds)
        self.assertEqual(len(tp_etoh["Angles"]), 13)
        etoh_angles = [[1, 0, 4], [1, 0, 5], [1, 0, 6], [4, 0, 5], [4, 0, 6],
                       [5, 0, 6], [0, 1, 2], [0, 1, 7], [0, 1, 8], [2, 1, 7],
                       [2, 1, 8], [7, 1, 8], [1, 2, 3]]
        np.testing.assert_array_equal(tp_etoh["Angles"], etoh_angles)
        self.assertEqual(len(tp_etoh["Dihedrals"]), 12)
        etoh_dihedrals = [[4, 0, 1, 2], [4, 0, 1, 7], [4, 0, 1, 8],
                          [5, 0, 1, 2], [5, 0, 1, 7], [5, 0, 1, 8],
                          [6, 0, 1, 2], [6, 0, 1, 7], [6, 0, 1, 8],
                          [0, 1, 2, 3], [7, 1, 2, 3], [8, 1, 2, 3]]
        np.testing.assert_array_equal(tp_etoh["Dihedrals"], etoh_dihedrals)
        # bond flag to off
        topo_etoh0 = Topology.from_bonding(molecule=etoh, bond=False,
                                           angle=True, dihedral=True)
        self.assertIsNone(topo_etoh0.topologies)
        # angle or dihedral flag to off
        topo_etoh1 = Topology.from_bonding(molecule=etoh, angle=False)
        self.assertNotIn("Angles", topo_etoh1.topologies)
        topo_etoh2 = Topology.from_bonding(molecule=etoh, dihedral=False)
        self.assertNotIn("Dihedrals", topo_etoh2.topologies)


class ForceFieldTest(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        mass_info = [("A", "H"), ("B", Element("C")),
                     ("C", Element("O")), ("D", 1.00794)]
        nonbond_coeffs = [[1, 1, 1.1225], [1, 1.175, 1.31894],
                          [1, 1.55, 1.73988], [1, 1, 1.1225 ],
                          [1, 1.35, 4], [1, 1.725, 1.93631],
                          [1, 1.175, 1.31894], [1, 2.1, 4],
                          [1, 1.55, 1.73988], [1, 1,  1.1225 ]]
        topo_coeffs = {"Bond Coeffs": [{"coeffs": [50, 0.659469],
                                        "types": [("A", "B"), ("C", "D")]},
                                       {"coeffs": [50, 0.855906],
                                        "types": [("B", "C")]}]}
        cls.virus = ForceField(mass_info=mass_info,
                               nonbond_coeffs=nonbond_coeffs,
                               topo_coeffs=topo_coeffs)
        cls.ethane = ForceField.from_file(os.path.join(test_dir,
                                                       "ff_ethane.yaml"))

    def test_init(self):
        v = self.virus
        self.assertListEqual(v.mass_info, [("A", 1.00794), ("B", 12.0107),
                                           ("C", 15.9994), ("D", 1.00794)])
        self.assertEqual(v.masses.at[3, "mass"], 15.9994)
        v_ff = v.force_field
        self.assertNotIn("Pair Coeffs", v_ff)
        self.assertEqual(v_ff["PairIJ Coeffs"].iat[5, 4], 1.93631)
        self.assertEqual(v_ff["Bond Coeffs"].at[2, "coeff2"], 0.855906)
        v_maps = v.maps
        self.assertDictEqual(v_maps["Atoms"],
                             {"A": 1, "B": 2, "C": 3, "D": 4})
        self.assertDictEqual(v_maps["Bonds"],
                             {("A", "B"): 1, ("C", "D"): 1,
                              ("B", "A"): 1, ("D", "C"): 1,
                              ("B", "C"): 2, ("C", "B"): 2})
        e = self.ethane
        self.assertEqual(e.masses.at[1, "mass"], 12.01115)
        e_ff = e.force_field
        self.assertNotIn("PairIJ Coeffs", e_ff)
        self.assertEqual(e_ff["Pair Coeffs"].at[1, "coeff2"], 3.854)
        self.assertEqual(e_ff["Bond Coeffs"].at[2, "coeff4"], 844.6)
        self.assertEqual(e_ff["Angle Coeffs"].at[2, "coeff4"], -2.4318)
        self.assertEqual(e_ff["Dihedral Coeffs"].at[1, "coeff1"], -0.1432)
        self.assertEqual(e_ff["Improper Coeffs"].at[2, "coeff2"], 0.0)
        self.assertEqual(e_ff["BondBond Coeffs"].at[2, "coeff1"], 5.3316)
        self.assertEqual(e_ff["BondAngle Coeffs"].at[1, "coeff3"], 1.53)
        self.assertEqual(e_ff["MiddleBondTorsion Coeffs"].at[1, "coeff1"],
                         -14.261)
        self.assertEqual(e_ff["EndBondTorsion Coeffs"].at[1, "coeff1"], 0.213)
        self.assertEqual(e_ff["AngleTorsion Coeffs"].at[1, "coeff3"], -0.2466)
        self.assertEqual(e_ff["AngleAngleTorsion Coeffs"].at[1, "coeff1"],
                         -12.564)
        self.assertEqual(e_ff["BondBond13 Coeffs"].at[1, "coeff1"], 0.0)
        self.assertEqual(e_ff["AngleAngle Coeffs"].at[1, "coeff2"], -0.4825)
        e_maps = e.maps
        self.assertDictEqual(e_maps["Atoms"], {"c4": 1, "h1": 2})
        self.assertDictEqual(e_maps["Bonds"],{("c4", "c4"): 1,
                                              ("c4", "h1"): 2,
                                              ("h1", "c4"): 2})
        self.assertDictEqual(e_maps["Angles"], {("c4", "c4", "h1"): 1,
                                                ("h1", "c4", "c4"): 1,
                                                ("h1", "c4", "h1"): 2})
        self.assertEqual(e_maps["Impropers"], {("c4", "c4", "h1", "h1"): 1,
                                               ("c4", "h1", "c4", "h1"): 1,
                                               ("h1", "h1", "c4", "c4"): 1,
                                               ("h1", "c4", "h1", "c4"): 1,
                                               ("h1", "c4", "h1", "h1"): 2,
                                               ("h1", "h1", "c4", "h1"): 2})

    def test_to_file(self):
        filename = "ff_test.yaml"
        v = self.virus
        v.to_file(filename=filename)
        yaml = YAML(typ="safe")
        with open(filename, "r") as f:
            d = yaml.load(f)
        self.assertListEqual(d["mass_info"], [list(m) for m in v.mass_info])
        self.assertListEqual(d["nonbond_coeffs"], v.nonbond_coeffs)

    def test_from_file(self):
        e = self.ethane
        self.assertListEqual(e.mass_info, [("c4", 12.01115), ("h1", 1.00797)])
        np.testing.assert_array_equal(e.nonbond_coeffs, [[0.062, 3.854],
                                                         [0.023, 2.878]])
        e_tc = e.topo_coeffs
        self.assertIn("Bond Coeffs", e_tc)
        self.assertIn("BondAngle Coeffs", e_tc["Angle Coeffs"][0])
        self.assertIn("BondBond Coeffs", e_tc["Angle Coeffs"][0])
        self.assertIn("AngleAngleTorsion Coeffs", e_tc["Dihedral Coeffs"][0])
        self.assertIn("AngleTorsion Coeffs", e_tc["Dihedral Coeffs"][0])
        self.assertIn("BondBond13 Coeffs", e_tc["Dihedral Coeffs"][0])
        self.assertIn("EndBondTorsion Coeffs", e_tc["Dihedral Coeffs"][0])
        self.assertIn("MiddleBondTorsion Coeffs", e_tc["Dihedral Coeffs"][0])
        self.assertIn("AngleAngle Coeffs", e_tc["Improper Coeffs"][0])

    def test_from_dict(self):
        d = self.ethane.as_dict()
        json_str = json.dumps(d)
        decoded = ForceField.from_dict(json.loads(json_str))
        self.assertListEqual(decoded.mass_info, self.ethane.mass_info)
        self.assertListEqual(decoded.nonbond_coeffs,
                             self.ethane.nonbond_coeffs)
        self.assertDictEqual(decoded.topo_coeffs, self.ethane.topo_coeffs)

    @classmethod
    def tearDownClass(cls):
        if os.path.exists("ff_test.yaml"):
            os.remove("ff_test.yaml")


if __name__ == "__main__":
    unittest.main()
