#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

status=0
files=$(git diff --diff-filter=d --cached --name-only | grep -E 'pymatgen.*\.(py)$' | sed '/test_/d')
files=`echo $files | tr '\n' ' '`
echo "Check code styles for $files"
pycodestyle pymatgen/dao.py $files
if [ $? -ne 0 ]; then
  echo "Bad code style detected by pycodestyle. Fix before commit."
  exit 1
fi
echo "Flake8 for $files"
flake8 pymatgen/dao.py $files
if [ $? -ne 0 ]; then
  echo "Bad code style detected by flake8. Fix before commit."
  exit 1
fi
echo "Check doc styles for $files"
pydocstyle --match='(?!test_).*\.py' pymatgen/dao.py $files
if [ $? -ne 0 ]; then
  echo "Bad doc style detected. Fix before commit."
  exit 1
fi
