from __future__ import annotations

import re
from collections import defaultdict
from itertools import islice
from typing import TYPE_CHECKING, Any

import numpy as np

from pymatgen.core.structure import Structure
from pymatgen.electronic_structure.core import Spin
from pymatgen.electronic_structure.dos import Dos
from pymatgen.io.lobster.future.core import LobsterFile
from pymatgen.io.lobster.future.utils import make_json_compatible
from pymatgen.io.lobster.future.versioning import version_processor

if TYPE_CHECKING:
    from typing import ClassVar

    from pymatgen.core.structure import IStructure
    from pymatgen.util.typing import PathLike


class DOSCAR(LobsterFile):
    """Represents LOBSTER's projected DOS and local projected DOS.

    This class parses and stores data from the DOSCAR file generated by LOBSTER,
    which contains information about the total and projected density of states
    (DOS) for a quantum-chemical calculation performed with VASP.

    Attributes:
        completedos (LobsterCompleteDos): Complete DOS data.
        pdos (list[dict[str, dict[Spin, np.ndarray]]]): Projected DOS data.
            Access as `pdos[atomindex]['orbitalstring'][Spin.up/Spin.down]`.
        tdos (Dos): Total density of states.
        energies (np.ndarray): Energies at which the DOS was calculated
            (in eV, relative to Efermi).
        tdensities (dict[Spin, np.ndarray]): Total density arrays for each spin channel.
        itdensities (dict[Spin, np.ndarray]): Integrated total density arrays for each spin channel.
        is_spin_polarized (bool): Whether the system is spin polarized.
    """

    is_lcfo: ClassVar[bool] = False

    def __init__(
        self,
        filename: PathLike | None = None,
        structure_file: PathLike | None = "POSCAR",
        structure: IStructure | None = None,
        process_immediately: bool = True,
    ) -> None:
        """Initialize a DOSCAR object.

        Args:
            filename (PathLike | None): Path to the DOSCAR file, typically "DOSCAR.lobster".
            structure_file (PathLike | None): Path to the structure file. For VASP, typically "POSCAR".
                Ignored if `structure` is provided directly.
            structure (IStructure | None): Structure object. If provided, `structure_file` is ignored.
            process_immediately (bool): Whether to process the file immediately upon initialization.

        Raises:
            ValueError: If neither `structure_file` nor `structure` is provided.
        """
        if structure is not None:
            self.structure = structure
        elif structure_file is not None:
            self.structure = Structure.from_file(structure_file)
        else:
            raise ValueError(
                "Either `structure_file` or `structure` args must be provided."
            )

        super().__init__(
            filename=filename,
            process_immediately=process_immediately,
        )

    @version_processor()
    def process(self) -> None:
        """Process the DOSCAR file and extract DOS data.

        Parses the DOSCAR file to extract total DOS, projected DOS, energies,
        and integrated densities. Sets the appropriate attributes based on
        whether the calculation is spin-polarized.

        Raises:
            ValueError: If the DOSCAR file format is invalid or spin polarization
                cannot be determined.
        """
        tdensities, itdensities = {}, {}
        dos, orbitals = [], []

        self.spins = [Spin.up]

        header_regex = r"\s*\S+\s+\S+\s+(\d+)\s+(\S+)\s+1\.0+(?:;.*;(.*))?"

        efermi = None
        ndos = 0

        lines_iter = iter(self.iterate_lines())
        for line in islice(lines_iter, 5, None):
            if match := re.match(header_regex, line):
                ndos = int(match.group(1))

                if efermi is None:
                    efermi = float(match.group(2))

                if match.group(3):
                    orbitals += [[orb.strip() for orb in match.group(3).split()]]

            tmp_dos = []
            if line.strip():
                for _ in range(ndos):
                    line = next(lines_iter)
                    tmp_dos.append(line.split())

                dos.append(np.array(tmp_dos, dtype=float))

        doshere = dos[0]
        if len(doshere[0, :]) == 5:
            self.spins.append(Spin.down)
        elif len(doshere[0, :]) == 3:
            pass
        else:
            raise ValueError(
                "There is something wrong with the DOSCAR. Can't extract spin polarization."
            )

        energies = doshere[:, 0]
        if not self.is_spin_polarized:
            tdensities[Spin.up] = doshere[:, 1]
            itdensities[Spin.up] = doshere[:, 2]
            pdoss = []
            spin = Spin.up
            for atom in range(len(dos) - 1):
                pdos = defaultdict(dict)
                data = dos[atom + 1]
                _, ncol = data.shape

                for orb_num, j in enumerate(range(1, ncol)):
                    orb = orbitals[atom][orb_num]
                    pdos[orb][spin] = data[:, j]
                pdoss.append(pdos)
        else:
            tdensities[Spin.up] = doshere[:, 1]
            tdensities[Spin.down] = doshere[:, 2]
            itdensities[Spin.up] = doshere[:, 3]
            itdensities[Spin.down] = doshere[:, 4]
            pdoss = []
            for atom in range(len(dos) - 1):
                pdos = defaultdict(dict)
                data = dos[atom + 1]
                _, ncol = data.shape
                orb_num = 0
                for j in range(1, ncol):
                    spin = Spin.down if j % 2 == 0 else Spin.up
                    orb = orbitals[atom][orb_num]
                    pdos[orb][spin] = data[:, j]
                    if j % 2 == 0:
                        orb_num += 1
                pdoss.append(pdos)

        if efermi is None:
            raise ValueError(
                "There is something wrong with the DOSCAR. Can't find efermi."
            )

        self.efermi = efermi
        self.pdos = pdoss
        self.tdos = Dos(efermi, energies, tdensities)
        self.energies = energies
        self.tdensities = tdensities
        self.itdensities = itdensities

    @property
    def is_spin_polarized(self) -> bool:
        """Whether the system is spin polarized.

        Returns:
            bool: True if the system is spin polarized, False otherwise.
        """
        return len(self.spins) == 2

    def as_dict(self) -> dict[str, Any]:
        """Convert the `DOSCAR` object to a dictionary for serialization.

        Returns:
            dict[str, Any]: Dictionary representation of the `DOSCAR` object.
        """
        dictionary = super().as_dict()

        dictionary["attributes"]["is_lcfo"] = self.is_lcfo
        dictionary["attributes"]["pdos"] = make_json_compatible(self.pdos)
        dictionary["attributes"]["spins"] = self.spins
        dictionary["attributes"]["tdos"] = self.tdos.as_dict()
        dictionary["attributes"]["energies"] = self.energies
        dictionary["attributes"]["tdensities"] = make_json_compatible(self.tdensities)
        dictionary["attributes"]["itdensities"] = make_json_compatible(self.itdensities)
        dictionary["attributes"]["efermi"] = self.efermi

        dictionary["kwargs"] = {
            "structure": self.structure.as_dict(),
            "filename": self.filename,
        }

        return dictionary

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> DOSCAR:
        """Create a `DOSCAR` object from a dictionary.

        Args:
            d (dict[str, Any]): A dictionary representation of a `DOSCAR` object.

        Returns:
            DOSCAR: The `DOSCAR` object created from the dictionary.
        """
        instance = super().from_dict(d)

        for spin, value in list(instance.tdensities.items()):
            instance.tdensities[Spin(int(spin))] = value
        for spin, value in list(instance.itdensities.items()):
            instance.itdensities[Spin(int(spin))] = value

        return instance

    @classmethod
    def get_default_filename(cls) -> str:
        """Get the default filename for the DOSCAR.

        Returns:
            str: Default filename string. "DOSCAR.lobster" for regular DOSCAR,
            "DOSCAR.LCFO.lobster" for LCFO analysis.
        """
        return "DOSCAR.lobster" if not cls.is_lcfo else "DOSCAR.LCFO.lobster"


class DOSCAR_LCFO(DOSCAR):
    """Represents LOBSTER's projected DOS and local projected DOS for LCFO analysis.

    This class handles DOSCAR files generated from LCFO analysis, which have
    a different format than regular DOSCAR files.

    Attributes:
        is_lcfo (bool): Class variable indicating this is for LCFO analysis. Always True.
    """

    is_lcfo: ClassVar[bool] = True
