Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Si             3s            0.52            0.61
                          3p_y            0.38            0.52
                          3p_z            0.37            0.52
                          3p_x            0.37            0.52
                         total            1.64            2.16

      2      Si             3s            0.52            0.61
                          3p_y            0.38            0.52
                          3p_z            0.37            0.52
                          3p_x            0.37            0.52
                         total            1.64            2.16

      3      Si             3s            0.52            0.61
                          3p_y            0.37            0.51
                          3p_z            0.37            0.52
                          3p_x            0.38            0.52
                         total            1.64            2.16

      4       O             2s            1.80            1.60
                          2p_y            1.77            1.75
                          2p_z            1.79            1.77
                          2p_x            1.82            1.80
                         total            7.18            6.92

      5       O             2s            1.80            1.60
                          2p_y            1.83            1.82
                          2p_z            1.79            1.77
                          2p_x            1.75            1.73
                         total            7.18            6.92

      6       O             2s            1.80            1.60
                          2p_y            1.78            1.76
                          2p_z            1.79            1.77
                          2p_x            1.81            1.79
                         total            7.18            6.92

      7       O             2s            1.80            1.60
                          2p_y            1.78            1.76
                          2p_z            1.79            1.77
                          2p_x            1.81            1.79
                         total            7.18            6.92

      8       O             2s            1.80            1.60
                          2p_y            1.77            1.75
                          2p_z            1.79            1.77
                          2p_x            1.82            1.80
                         total            7.18            6.92

      9       O             2s            1.80            1.60
                          2p_y            1.83            1.82
                          2p_z            1.79            1.77
                          2p_x            1.75            1.73
                         total            7.18            6.92

