  COHP#  atomMU  atomNU     distance          ICOHP(eF) avg. over # bonds  for spin  1
      1     Fe8     Fe7      2.83189           -0.10218                 2
      2     Fe8     Fe9      2.45249           -0.28485                 1
  COHP#  atomMU  atomNU     distance          ICOHP(eF) avg. over # bonds  for spin  2
      1     Fe8     Fe7      2.83189           -0.19701                 2
      2     Fe8     Fe9      2.45249           -0.58279                 1
