  COOP#  atomMU  atomNU     distance          ICOOP(eF) avg. over # bonds  for spin  1
      1     Fe8     Fe7      2.83189           -0.11389                 2
      2     Fe8     Fe9      2.45249           -0.04087                 1
  COOP#  atomMU  atomNU     distance          ICOOP(eF) avg. over # bonds  for spin  2
      1     Fe8     Fe7      2.83189           -0.20828                 2
      2     Fe8     Fe9      2.45249           -0.05756                 1
