name: Report a Bug
description: Use this template to report a Pymatgen-related bug
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ### Try the new Codespaces, setup env and collect info made easy.
        <details>
          <summary>🚀 Click to Show the Codespaces Guide</summary>
          <img width="300" alt="Create codespace" src="https://github.com/materialsproject/pymatgen/assets/80093591/482181f8-d7e1-49b4-8382-2d948ed4e550">

          * Open up the [pymatgen repo](https://github.com/materialsproject/pymatgen) in your web browser.
          * Click the green `Code` button at the top-right corner of the repo, and switch to the `Codespaces` panel.
          * Click `Create code space on master` to create a new codespace, or to return to an existing codespace.
        </details>

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Use `python --version` to get Python version
      placeholder: ex. Python 3.11.5
    validations:
      required: true

  - type: input
    id: pmg-version
    attributes:
      label: Pymatgen version
      description: Use `pip show pymatgen | grep Version` to get Pymatgen version
      placeholder: ex. 2023.12.18
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system version
      placeholder: ex. Ubuntu 22.04 LTS
    validations:
      required: false

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: What bad behavior do you see?
      render: Python
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to see?
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Minimal example
      description: Please provide a minimal code snippet to reproduce this bug.
      render: Python
    validations:
      required: false

  - type: textarea
    id: files
    attributes:
      label: Relevant files to reproduce this bug
      description: Please upload relevant files to help reproduce this bug, or logs if helpful.
    validations:
      required: false
