name: Feature Reqest
description: Use this template to request a new feature
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Requested
      description: Specify the feature and provide examples or use cases.
      placeholder: e.g., Generate atomic structures with specific symmetry constraints ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Share your thoughts on how the feature could be implemented.
      placeholder: e.g., Implement through a new method ...
    validations:
      required: true

  - type: textarea
    id: relevant
    attributes:
      label: Relevant Information
      description: Include additional context or links helpful for understanding or implementing the feature.
      placeholder: e.g., Context about use cases, related discussions, or relevant literature ...
    validations:
      required: false
