#!/bin/bash

sphinx-apidoc -o . -f ../pymatgen
rm *tests.rst
for filename in `ls -d pymatgen.*.rst`
do
    sed "/tests/d" $filename > temp.rst
    mv temp.rst $filename
done
make html

cp nature_mp.css ../../docs/pymatgen/html/static/nature.css
cp favicon.ico ../../docs/pymatgen/html/static/favicon.ico
cp pymatgen.png ../../docs/pymatgen/html/static/pymatgen.png